feat: Add initial implementation

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-
-set -euo pipefail
+set -eufET -o pipefail
+shopt -s inherit_errexit
 
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "${current_script_path}")")
@@ -11,16 +11,151 @@ source "${plugin_dir}/lib/utils.bash"
 : "${ASDF_DOWNLOAD_PATH:?ASDF_DOWNLOAD_PATH is not specified}"
 : "${ASDF_INSTALL_VERSION:?ASDF_INSTALL_VERSION is not specified}"
 
-mkdir -p "${ASDF_DOWNLOAD_PATH}"
+function download_release() {
+	local version="${1:?version parameter missing}"
+	local filename="${2:?filename parameter missing}"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}-${ASDF_INSTALL_VERSION}.tar.gz"
+	local android_sdk_package_name="cmdline-tools"
 
-# Download tar.gz file to the download directory
-download_release "${ASDF_INSTALL_VERSION}" "${release_file}"
+	# Determine operation system and architecture
+	local android_sdk_os
+	case "${OSTYPE}" in
+		"linux"*) android_sdk_os="linux" ;;
+		"darwin"*) android_sdk_os="macosx" ;;
+		"cygwin" | "msys") android_sdk_os="windows" ;;
+		*) {
+			error "Unsupported OS type '${OSTYPE}'"
+			return 2
+		} ;;
+	esac
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "${release_file}" -C "${ASDF_DOWNLOAD_PATH}" --strip-components=1 || fail "Could not extract ${release_file}"
+	local android_sdk_arch
+	case "${HOSTTYPE}" in
+		"x86_64") android_sdk_arch="x64" ;;
+		"arm64") android_sdk_arch="aarch64" ;;
+		*) {
+			error "Unsupported host type '${HOSTTYPE}'"
+			return 3
+		} ;;
+	esac
 
-# Remove the tar.gz file since we don't need to keep it
-rm "${release_file}"
+	echo "* Searching for Android SDK package ${android_sdk_package_name} with version ${version} for OS ${android_sdk_os}:${android_sdk_arch}"
+
+	# Download Android SDK repository metadata
+	local android_sdk_metadata_xml
+	android_sdk_metadata_xml="$(fetch_android_sdk_metadata)" || {
+		error "Could not fetch Android SDK metadata"
+		return 4
+	}
+
+	# Extract Android SDK tool metadata
+	local android_sdk_tool_metadata
+	android_sdk_tool_metadata="$(parse_android_sdk_metadata "${android_sdk_metadata_xml}" "${android_sdk_package_name}")" ||
+		{
+			error "Could not parse Android SDK tool metadata"
+			return 5
+		}
+
+	# Extract platform-specific metadata from Android SDK tool metadata
+	local android_sdk_tool_metadata_parse_command='
+		# Extract metadata for requested Android SDK package version
+		.[] | select(.+@path == strenv(ANDROID_SDK_PACKAGE_NAME) + ";" + strenv(ANDROID_SDK_PACKAGE_VERSION)) |
+
+		# Extract platform-specific Android SDK package metadata
+		.archives.archive[] | select(.host-os == strenv(ANDROID_SDK_OS) and (has(.host-arch) == false or .host-arch == strenv(ANDROID_SDK_ARCH))) |
+
+		# Extract Android SDK package archive metadata
+		.complete
+	'
+
+	local android_sdk_tool_archive_metadata_yaml
+	android_sdk_tool_archive_metadata_yaml="$(
+		ANDROID_SDK_PACKAGE_NAME="${android_sdk_package_name}" ANDROID_SDK_PACKAGE_VERSION="${version}" \
+			ANDROID_SDK_OS="${android_sdk_os}" ANDROID_SDK_ARCH="${android_sdk_arch}" \
+			yq --exit-status --input-format yaml --output-format yaml "${android_sdk_tool_metadata_parse_command}" <<< "${android_sdk_tool_metadata}"
+	)" || {
+		error "Could not find Android SDK package metadata"
+		return 6
+	}
+
+	# Extract download URL and checksum for Android SDK tool
+	local android_sdk_tool_archive_checksum
+	android_sdk_tool_archive_checksum="$(
+		yq --exit-status --input-format yaml --output-format yaml --unwrapScalar '.checksum.+content' <<< "${android_sdk_tool_archive_metadata_yaml}"
+	)" || {
+		error "Could not extract checksum from Android SDK archive metadata"
+		return 7
+	}
+
+	local android_sdk_tool_archive_checksum_type
+	android_sdk_tool_archive_checksum_type="$(
+		yq --exit-status --input-format yaml --output-format yaml --unwrapScalar '.checksum.+@type' <<< "${android_sdk_tool_archive_metadata_yaml}"
+	)" || {
+		error "Could not extract checksum type from Android SDK archive metadata"
+		return 8
+	}
+
+	local android_sdk_tool_archive_url
+	android_sdk_tool_archive_url="$(
+		yq --exit-status --input-format yaml --output-format yaml --unwrapScalar '.url' <<< "${android_sdk_tool_archive_metadata_yaml}"
+	)" || {
+		error "Could not extract url from Android SDK archive metadata"
+		return 9
+	}
+
+	if [[ "${android_sdk_tool_archive_url}" != *"://"* ]]; then
+		# Prepend Android SDK base URL in case the tool archive URL is relative
+		local android_sdk_base_url
+		android_sdk_base_url="$(get_android_sdk_base_url)"
+
+		android_sdk_tool_archive_url="${android_sdk_base_url}/${android_sdk_tool_archive_url}"
+	fi
+
+	# Download Android SDK tool archive
+	local android_sdk_base_url
+	android_sdk_base_url="$(get_android_sdk_base_url)"
+
+	curl "${curl_opts[@]}" --output "${filename}" --continue-at - "${android_sdk_tool_archive_url}" ||
+		{
+			error "Could not download ${android_sdk_tool_archive_url}"
+			return 10
+		}
+
+	# Verify Android SDK tool archive
+	local actual_android_sdk_tool_archive_checksum
+	actual_android_sdk_tool_archive_checksum="$(cksum --algorithm "${android_sdk_tool_archive_checksum_type}" --untagged "${filename}" | cut -f 1 -d " ")"
+
+	if [[ "${actual_android_sdk_tool_archive_checksum}" != "${android_sdk_tool_archive_checksum}" ]]; then
+		error "Failed to verify checksum. Expected ${android_sdk_tool_archive_checksum_type} '${android_sdk_tool_archive_checksum}' but got '${actual_android_sdk_tool_archive_checksum}'"
+		return 11
+	fi
+}
+
+function main() {
+	local download_path="${1:-download path parameter is required}"
+	local install_version="${2:-install version parameter is required}"
+
+	mkdir -p "${download_path}"
+	local release_file="${download_path}/${TOOL_NAME}-${install_version}.zip"
+
+	# Download tool archive to the download directory
+	echo "* Downloading ${TOOL_NAME} release ${install_version}..."
+	download_release "${install_version}" "${release_file}" ||
+		{
+			local return_code=$?
+			error "Failed to download Android SDK Command-line tools ${install_version}"
+			return "${return_code}"
+		}
+
+	#  Extract contents of tar.gz file into the download directory
+	echo "* Extracting ${TOOL_NAME} release ${install_version}..."
+	unzip -q -d "${download_path}" "${release_file}" || {
+		error "Could not extract ${release_file}"
+		return 12
+	}
+
+	# Remove the tar.gz file since we don't need to keep it
+	rm "${release_file}"
+}
+
+main "${ASDF_DOWNLOAD_PATH}" "${ASDF_INSTALL_VERSION}"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-
-set -euo pipefail
+set -eufET -o pipefail
+shopt -s inherit_errexit
 
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "${current_script_path}")")
@@ -10,6 +10,56 @@ source "${plugin_dir}/lib/utils.bash"
 
 : "${ASDF_INSTALL_TYPE:?ASDF_INSTALL_TYPE is not specified}"
 : "${ASDF_INSTALL_VERSION:?ASDF_INSTALL_VERSION is not specified}"
+: "${ASDF_DOWNLOAD_PATH:?ASDF_DOWNLOAD_PATH is not specified}"
 : "${ASDF_INSTALL_PATH:?ASDF_INSTALL_PATH is not specified}"
 
-install_version "${ASDF_INSTALL_TYPE}" "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
+function main() {
+	local install_type="${1:-install type parameter is required}"
+	local version="${2:-version parameter is required}"
+	local download_path="${3:-download path parameter is required}"
+	local install_path="${4:-install path parameter is required}"
+
+	echo "* Installing ${TOOL_NAME} release ${version}..."
+
+	if [[ "${install_type}" != "version" ]]; then
+		error "asdf-${TOOL_NAME} supports release installs only"
+		return 2
+	fi
+
+	local android_sdk_download_path="${download_path}/cmdline-tools"
+	if [[ ! -d "${android_sdk_download_path}" ]]; then
+		error "Download path does not exist: ${download_path}"
+		return 3
+	fi
+
+	local android_sdk_install_path="${install_path}/cmdline-tools/${version}"
+
+	(
+		# Copy Android SDK files from download to install location
+		mkdir -p "${android_sdk_install_path}"
+		cp --recursive --preserve=mode,timestamps "${android_sdk_download_path}/." "${android_sdk_install_path}"
+
+		# Test installation
+		local tool_executable_path="${android_sdk_install_path}/bin/sdkmanager"
+		if ! [[ -x "${tool_executable_path}" ]]; then
+			fail 4 "Expected ${tool_executable_path} to be executable."
+		fi
+
+		local tool_version_output
+		tool_version_output="$("${tool_executable_path}" --version)" || fail 5 "Failed to test validity of ${tool_executable_path}: ${tool_version_output}"
+		if [[ "${tool_version_output}" != "${version}" ]]; then
+			fail 6 "Expected ${tool_executable_path} to return version '${version}', but got '${tool_version_output}'"
+		fi
+
+		echo "Android SDK Command-line tools ${version} installation was successful!"
+	) || {
+		local return_code=$?
+
+		find "${install_path}/" -mindepth 1 -delete
+
+		error "An error occurred while installing Android SDK Command-line tools ${version}."
+		return "${return_code}"
+	}
+}
+
+main "${ASDF_INSTALL_TYPE}" "${ASDF_INSTALL_VERSION}" "${ASDF_DOWNLOAD_PATH}" "${ASDF_INSTALL_PATH}"
diff --git a/bin/latest-stable b/bin/latest-stable
--- a/bin/latest-stable
+++ b/bin/latest-stable
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-
-set -euo pipefail
+set -eufET -o pipefail
+shopt -s inherit_errexit
 
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "${current_script_path}")")
@@ -8,22 +8,43 @@ plugin_dir=$(dirname "$(dirname "${current_script_path}")")
 # shellcheck source=../lib/utils.bash
 . "${plugin_dir}/lib/utils.bash"
 
-curl_opts=(-sI)
+function main() {
+	# Download Android SDK repository metadata
+	local android_sdk_metadata_xml
+	android_sdk_metadata_xml="$(fetch_android_sdk_metadata)" || {
+		error "Could not fetch Android SDK metadata"
+		return 2
+	}
 
-if [[ -n "${GITHUB_API_TOKEN:-}" ]]; then
-	curl_opts=("${curl_opts[@]}" -H "Authorization: token ${GITHUB_API_TOKEN}")
-fi
+	# Extract Android SDK tool metadata
+	local android_sdk_tool_metadata
+	android_sdk_tool_metadata="$(parse_android_sdk_metadata "${android_sdk_metadata_xml}" "cmdline-tools")" ||
+		{
+			error "Could not parse Android SDK tool metadata"
+			return 3
+		}
 
-# curl of REPO/releases/latest is expected to be a 302 to another URL
-# when no releases redirect_url="REPO/releases"
-# when there are releases redirect_url="REPO/releases/tag/v<VERSION>"
-redirect_url=$(curl "${curl_opts[@]}" "${GH_REPO}/releases/latest" | sed -n -e "s|^location: *||p" | sed -n -e "s|\r||p")
-version=
-printf "redirect url: %s\n" "${redirect_url}" >&2
-if [[ "${redirect_url}" == "${GH_REPO}/releases" ]]; then
-	version="$(list_all_versions | sort_versions | tail -n1 | xargs echo)"
-else
-	version="$(printf "%s\n" "${redirect_url}" | sed 's|.*/tag/v\{0,1\}||')"
-fi
+	# Extract latest stable Android SDK tool version
+	latest_stable_tool_version_parse_command='
+		# Filter for stable versions
+		filter(.channelRef.+@ref == "channel-0") |
 
-printf "%s\n" "${version}"
+		# Get last entry, which represents the highest version
+		.[-1] |
+
+		# Extract version
+		.+@path | split(";") | .[1]
+	'
+
+	local latest_stable_tool_version
+	latest_stable_tool_version="$(
+		yq --exit-status --input-format yaml --output-format yaml --unwrapScalar "${latest_stable_tool_version_parse_command}" <<< "${android_sdk_tool_metadata}"
+	)" || {
+		error "Could not extract latest stable Android SDK tool version"
+		return 4
+	}
+
+	printf "%s\n" "${latest_stable_tool_version}"
+}
+
+main
